import type { LocaleCode } from './locales'

const copy = {
  en: {
    dashboard: { flagship: 'Flagship mini-app', removeFavorite: 'Remove from favorites', addFavorite: 'Add to favorites', offline: 'Offline', private: 'Private', open: 'Open', communityBuilt: 'Community built', improve: 'Improve with us', flagshipTitle: '26 flagship tools, shaped by real use', flagshipHint: 'Start with a favorite, then tell us what should feel simpler.', joinTesters: 'Join testers', results: 'results', all: 'All', noMatch: 'No tool matched your search.', workspaceEyebrow: 'Flagship 4.0', workspaceTitle: 'Choose a workspace', workspaceHint: 'Start with a goal. PureHub connects the next useful action without uploading your work.', tools: 'tools', startWith: 'Start with', openTool: 'Open' },
    shell: { communityOnline: 'Community online', packOnDemand: 'Pack on demand', offlineReady: 'Offline ready', favorite: 'Favorite tool', promises: 'PureHub promises', noAds: 'No ads', privateFirst: 'Private first', loading: 'Loading tool', isolatedStorage: 'Isolated storage', localStorage: 'Local storage' },
    workflow: { ready: 'Ready', chooseInput: 'Choose input', privateWork: 'Private work', onDevice: 'On this device', result: 'Result', readyToUse: 'Ready to use', afterSuccess: 'After success', complete: 'Workflow complete', waiting: 'Workflow ready' },
    workspace: { related: 'Related workflow tools', workspace: 'Workspace' },
    engagement: { continue: 'Continue the workflow', testerTitle: 'Help test the core workflows.', testerHint: 'Try QR, OCR, and Deep Cleaner, then tell us one thing to improve.', helpedTitle: 'Did this result help?', helpedHint: 'One tap helps prioritize the next improvement. Share only when this result is worth passing on.', helpful: 'Helpful', itHelped: 'It helped', feedback: 'Feedback', share: 'Share', shareFailed: 'Could not share', finish: 'Finish one real task to unlock result feedback and sharing. PureHub does not interrupt while you are working.', privateFeedback: 'Private product feedback', closeFeedback: 'Close feedback', thankYou: 'Thank you. Your feedback is now in the PureHub support inbox.', general: 'General', bug: 'Bug', idea: 'Idea', device: 'Device', placeholder: 'What worked, what felt confusing, or what should change?', privacy: 'No account, device ID, or IP is stored.', sending: 'Sending…', send: 'Send', sendError: 'Could not send right now. Please try again.', usefulResult: 'A useful result from', shareDetail: 'Works without ads, tracking walls, or surprise paywalls.', keepOffline: 'Keep this tool available offline on Android', keepOfflineDetail: 'Continue this privacy-first workflow in the signed Android app.' },
  },
  vi: {
    dashboard: { flagship: 'Mini-app chủ lực', removeFavorite: 'Bỏ khỏi yêu thích', addFavorite: 'Thêm vào yêu thích', offline: 'Ngoại tuyến', private: 'Riêng tư', open: 'Mở', communityBuilt: 'Cộng đồng phát triển', improve: 'Cùng cải thiện', flagshipTitle: '26 công cụ chủ lực, hoàn thiện từ sử dụng thực tế', flagshipHint: 'Bắt đầu với công cụ yêu thích rồi cho chúng tôi biết điều gì cần đơn giản hơn.', joinTesters: 'Tham gia thử nghiệm', results: 'kết quả', all: 'Tất cả', noMatch: 'Không tìm thấy công cụ phù hợp.', workspaceEyebrow: 'Bộ công cụ 4.0', workspaceTitle: 'Chọn không gian làm việc', workspaceHint: 'Bắt đầu từ mục tiêu. PureHub nối bước hữu ích tiếp theo mà không tải dữ liệu của bạn lên.', tools: 'công cụ', startWith: 'Bắt đầu với', openTool: 'Mở' },
    shell: { communityOnline: 'Cộng đồng trực tuyến', packOnDemand: 'Tải gói khi cần', offlineReady: 'Sẵn sàng ngoại tuyến', favorite: 'Công cụ yêu thích', promises: 'Cam kết PureHub', noAds: 'Không quảng cáo', privateFirst: 'Ưu tiên riêng tư', loading: 'Đang tải công cụ', isolatedStorage: 'Vùng lưu trữ riêng', localStorage: 'Lưu trên thiết bị' },
    workflow: { ready: 'Sẵn sàng', chooseInput: 'Chọn dữ liệu', privateWork: 'Xử lý riêng tư', onDevice: 'Trên thiết bị', result: 'Kết quả', readyToUse: 'Sẵn sàng dùng', afterSuccess: 'Sau khi hoàn tất', complete: 'Đã hoàn tất quy trình', waiting: 'Quy trình sẵn sàng' },
    workspace: { related: 'Công cụ liên quan', workspace: 'Không gian làm việc' },
    engagement: { continue: 'Tiếp tục quy trình', testerTitle: 'Giúp thử các quy trình chính.', testerHint: 'Thử QR, OCR và Dọn dẹp sâu rồi góp ý một điều cần cải thiện.', helpedTitle: 'Kết quả này có hữu ích không?', helpedHint: 'Một lần chạm giúp ưu tiên nâng cấp tiếp theo. Chỉ chia sẻ khi kết quả đáng gửi cho người khác.', helpful: 'Hữu ích', itHelped: 'Có ích', feedback: 'Góp ý', share: 'Chia sẻ', shareFailed: 'Không thể chia sẻ', finish: 'Hoàn tất một tác vụ thực tế để mở góp ý và chia sẻ kết quả. PureHub không làm phiền khi bạn đang thao tác.', privateFeedback: 'Góp ý sản phẩm riêng tư', closeFeedback: 'Đóng góp ý', thankYou: 'Cảm ơn. Góp ý của bạn đã được gửi đến hộp thư hỗ trợ PureHub.', general: 'Chung', bug: 'Lỗi', idea: 'Ý tưởng', device: 'Thiết bị', placeholder: 'Điều gì hoạt động tốt, gây khó hiểu hoặc cần thay đổi?', privacy: 'Không lưu tài khoản, ID thiết bị hay địa chỉ IP.', sending: 'Đang gửi…', send: 'Gửi', sendError: 'Hiện chưa thể gửi. Vui lòng thử lại.', usefulResult: 'Kết quả hữu ích từ', shareDetail: 'Hoạt động không quảng cáo, không theo dõi và không phí bất ngờ.', keepOffline: 'Giữ công cụ này ngoại tuyến trên Android', keepOfflineDetail: 'Tiếp tục quy trình ưu tiên riêng tư trong ứng dụng Android đã ký.' },
  },
  zh: {
    dashboard: { flagship: '旗舰小工具', removeFavorite: '取消收藏', addFavorite: '添加收藏', offline: '离线', private: '隐私', open: '开放', communityBuilt: '社区共建', improve: '共同改进', flagshipTitle: '26 个旗舰工具，由真实使用持续打磨', flagshipHint: '先使用常用工具，再告诉我们哪里可以更简单。', joinTesters: '加入测试', results: '个结果', all: '全部', noMatch: '没有符合搜索的工具。', workspaceEyebrow: '旗舰 4.0', workspaceTitle: '选择工作区', workspaceHint: '从目标开始。PureHub 会连接下一步操作，不上传您的数据。', tools: '个工具', startWith: '从此开始', openTool: '打开' },
    shell: { communityOnline: '社区在线', packOnDemand: '按需下载包', offlineReady: '可离线使用', favorite: '收藏工具', promises: 'PureHub 承诺', noAds: '无广告', privateFirst: '隐私优先', loading: '正在加载工具', isolatedStorage: '独立存储', localStorage: '本机存储' },
    workflow: { ready: '准备就绪', chooseInput: '选择输入', privateWork: '隐私处理', onDevice: '在此设备上', result: '结果', readyToUse: '可以使用', afterSuccess: '完成后', complete: '流程已完成', waiting: '流程已就绪' },
    workspace: { related: '相关流程工具', workspace: '工作区' },
    engagement: { continue: '继续流程', testerTitle: '帮助测试核心流程。', testerHint: '试用二维码、OCR 和深度清理，并告诉我们一项需要改进的地方。', helpedTitle: '这个结果有帮助吗？', helpedHint: '轻点一次即可帮助确定下一项改进。仅在结果值得分享时发送。', helpful: '有帮助', itHelped: '有用', feedback: '反馈', share: '分享', shareFailed: '无法分享', finish: '完成一项实际任务后即可反馈和分享结果。PureHub 不会在操作时打扰您。', privateFeedback: '私密产品反馈', closeFeedback: '关闭反馈', thankYou: '谢谢。您的反馈已发送到 PureHub 支持收件箱。', general: '一般', bug: '错误', idea: '建议', device: '设备', placeholder: '哪些地方好用、令人困惑或需要改变？', privacy: '不保存账户、设备 ID 或 IP 地址。', sending: '正在发送…', send: '发送', sendError: '暂时无法发送，请重试。', usefulResult: '实用结果来自', shareDetail: '无广告、无跟踪墙，也没有意外付费。', keepOffline: '在 Android 上离线保留此工具', keepOfflineDetail: '在已签名的 Android 应用中继续隐私优先流程。' },
  },
  es: {
    dashboard: { flagship: 'Miniapp principal', removeFavorite: 'Quitar de favoritos', addFavorite: 'Añadir a favoritos', offline: 'Sin conexión', private: 'Privado', open: 'Abierto', communityBuilt: 'Creado por la comunidad', improve: 'Mejora con nosotros', flagshipTitle: '26 herramientas principales, mejoradas con uso real', flagshipHint: 'Empieza con una favorita y dinos qué debería ser más sencillo.', joinTesters: 'Unirse a las pruebas', results: 'resultados', all: 'Todas', noMatch: 'Ninguna herramienta coincide con la búsqueda.', workspaceEyebrow: 'Principal 4.0', workspaceTitle: 'Elige un espacio de trabajo', workspaceHint: 'Empieza con un objetivo. PureHub conecta la siguiente acción útil sin subir tus datos.', tools: 'herramientas', startWith: 'Empezar con', openTool: 'Abrir' },
    shell: { communityOnline: 'Comunidad en línea', packOnDemand: 'Paquete bajo demanda', offlineReady: 'Lista sin conexión', favorite: 'Herramienta favorita', promises: 'Compromisos de PureHub', noAds: 'Sin anuncios', privateFirst: 'Privacidad primero', loading: 'Cargando herramienta', isolatedStorage: 'Almacenamiento aislado', localStorage: 'Almacenamiento local' },
    workflow: { ready: 'Lista', chooseInput: 'Elige una entrada', privateWork: 'Proceso privado', onDevice: 'En este dispositivo', result: 'Resultado', readyToUse: 'Listo para usar', afterSuccess: 'Al terminar', complete: 'Flujo completado', waiting: 'Flujo listo' },
    workspace: { related: 'Herramientas relacionadas', workspace: 'Espacio de trabajo' },
    engagement: { continue: 'Continuar el flujo', testerTitle: 'Ayuda a probar los flujos principales.', testerHint: 'Prueba QR, OCR y Limpieza profunda, y cuéntanos una mejora.', helpedTitle: '¿Te ayudó este resultado?', helpedHint: 'Un toque ayuda a priorizar la siguiente mejora. Comparte solo si vale la pena.', helpful: 'Útil', itHelped: 'Me ayudó', feedback: 'Comentarios', share: 'Compartir', shareFailed: 'No se pudo compartir', finish: 'Termina una tarea real para activar comentarios y compartir. PureHub no interrumpe mientras trabajas.', privateFeedback: 'Comentarios privados del producto', closeFeedback: 'Cerrar comentarios', thankYou: 'Gracias. Tus comentarios ya están en la bandeja de soporte de PureHub.', general: 'General', bug: 'Error', idea: 'Idea', device: 'Dispositivo', placeholder: '¿Qué funcionó, qué fue confuso o qué debería cambiar?', privacy: 'No se guarda ninguna cuenta, ID del dispositivo ni IP.', sending: 'Enviando…', send: 'Enviar', sendError: 'No se pudo enviar ahora. Inténtalo de nuevo.', usefulResult: 'Un resultado útil de', shareDetail: 'Funciona sin anuncios, muros de rastreo ni pagos sorpresa.', keepOffline: 'Mantén esta herramienta sin conexión en Android', keepOfflineDetail: 'Continúa este flujo privado en la aplicación Android firmada.' },
  },
} as const satisfies Record<LocaleCode, object>

export function getProductCopy(locale: LocaleCode) {
  return copy[locale]
}
