import type { LocaleCode } from './locales'

type UiCopy = {
  shell: { skip: string; theme: string; communityUtilities: string; freeForever: string; freePromise: string; android: string; privacy: string; terms: string; openSource: string }
  settings: {
    eyebrow: string; title: string; appearance: string; appearanceHint: string; system: string; light: string; dark: string
    privacyCenter: string; privacyCenterHint: string; platform: string; platformHint: string; compare: string
    language: string; languageHint: string; tester: string; testerHint: string; counters: string; countersHint: string; dnt: string
    privacyPromise: string; privacyPromiseHint: string
  }
  community: {
    eyebrow: string; title: string; intro: string; telegram: string; telegramHint: string; openTelegram: string
    discussions: string; discussionsHint: string; joinDiscussions: string; bug: string; bugHint: string; createIssue: string
    suggest: string; suggestHint: string; shareIdea: string; earlyEyebrow: string; earlyTitle: string; earlyHint: string; goal: string
    toolTested: string; deviceReport: string; devicePlaceholder: string; send: string; sending: string; sent: string; sentHint: string; sendError: string; privacyNote: string
    roadmap: string; roadmapHint: string; votes: string; yourVote: string; loading: string; unavailable: string; voteNote: string
    getAndroid: string; releaseHint: string; contribute: string; testFlows: string; improveTranslations: string; share: string
  }
}

export const uiCopy: Record<LocaleCode, UiCopy> = {
  en: {
    shell: { skip: 'Skip to content', theme: 'Toggle theme', communityUtilities: 'Community utilities', freeForever: 'Free forever', freePromise: 'No ads. No mandatory account. Open source with the community.', android: 'Android', privacy: 'Privacy', terms: 'Terms', openSource: 'Open source' },
    settings: { eyebrow: 'PureHub preferences', title: 'Settings', appearance: 'Appearance', appearanceHint: 'Choose the theme that works best for you.', system: 'System', light: 'Light', dark: 'Dark', privacyCenter: 'Open Privacy & Trust Center', privacyCenterHint: 'Permissions, encrypted suite backup and local data controls', platform: 'Platform availability', platformHint: 'PureHub has 26 tools on Android and 26 in this PWA. Browser tools cannot silently clean files, change wallpaper, or access every device sensor; Android asks for those permissions only when you use the matching tool.', compare: 'Compare Android and PWA', language: 'Language', languageHint: 'English, Vietnamese, Chinese, and Spanish are available.', tester: 'Join Google Play testers', testerHint: 'Open the tester group in your browser to receive the closed-test opt-in link.', counters: 'Anonymous usage counters', countersHint: 'Share aggregate tool opens, helpful taps, and shares. PureHub does not send a user ID, device ID, content, or stored IP.', dnt: 'Disabled because Do Not Track is enabled in your browser.', privacyPromise: 'Privacy promise', privacyPromiseHint: 'PureHub has no ads and processes data on-device whenever possible. Camera, microphone, and sensor permissions are requested only when a tool genuinely needs them.' },
    community: { eyebrow: 'Community built', title: 'PureHub belongs to everyone', intro: 'No Pro codes, no paywalls, and no ads. Telegram keeps people connected while GitHub keeps the product transparent and open.', telegram: 'Telegram community', telegramHint: 'Discuss ideas, receive updates, and get help from the PureHub community.', openTelegram: 'Open Telegram', discussions: 'GitHub Discussions', discussionsHint: 'Ask questions, share feedback, follow announcements, and help shape the roadmap.', joinDiscussions: 'Join discussions', bug: 'Report a bug', bugHint: 'Share the device, tool, and steps needed for the community to reproduce an issue.', createIssue: 'Create issue', suggest: 'Suggest a mini app', suggestHint: 'Suggest a small, useful, local-first tool that can remain free and ad-free.', shareIdea: 'Share idea', earlyEyebrow: 'Early Testers', earlyTitle: 'Help polish our flagship tools', earlyHint: 'Test on your real phone and report one thing that worked, felt confusing, or failed. Our first goal is 20 useful device reports.', goal: 'Goal 20 reports', toolTested: 'Tool tested', deviceReport: 'Device report', devicePlaceholder: 'Android 14 / Samsung A54 — controls were clear, but the sound button was hard to find.', send: 'Send report', sending: 'Sending...', sent: 'Thank you. Your anonymous report is now in the community support inbox.', sentHint: 'Thank you', sendError: 'The report could not be sent. Please try again or use GitHub Discussions.', privacyNote: 'No account is required. Do not include your name, email, phone number, or other personal information.', roadmap: 'Community roadmap vote', roadmapHint: 'Choose the mini-app upgrade that should receive the next deep product pass.', votes: 'votes', yourVote: 'Your vote', loading: 'Loading roadmap…', unavailable: 'Roadmap is temporarily unavailable.', voteNote: 'One vote is stored only in this browser. No account or personal identifier is collected.', getAndroid: 'Get PureHub for Android', releaseHint: 'Signed APK releases, checksums, and changelog', contribute: 'Ways to contribute', testFlows: 'Test the app and community flows', improveTranslations: 'Improve translations', share: 'Share PureHub with someone who needs it' },
  },
  vi: {
    shell: { skip: 'Chuyển đến nội dung', theme: 'Đổi giao diện', communityUtilities: 'Tiện ích cộng đồng', freeForever: 'Miễn phí mãi mãi', freePromise: 'Không quảng cáo. Không bắt buộc tài khoản. Mã nguồn mở cùng cộng đồng.', android: 'Android', privacy: 'Quyền riêng tư', terms: 'Điều khoản', openSource: 'Mã nguồn mở' },
    settings: { eyebrow: 'Tùy chọn PureHub', title: 'Cài đặt', appearance: 'Giao diện', appearanceHint: 'Chọn giao diện phù hợp nhất với bạn.', system: 'Theo hệ thống', light: 'Sáng', dark: 'Tối', privacyCenter: 'Mở Trung tâm Quyền riêng tư & Tin cậy', privacyCenterHint: 'Quyền truy cập, sao lưu bộ công cụ được mã hóa và dữ liệu cục bộ', platform: 'Khả dụng trên nền tảng', platformHint: 'PureHub có 26 công cụ trên Android và 26 công cụ trong PWA này. Trình duyệt không thể âm thầm dọn tệp, thay hình nền hoặc truy cập mọi cảm biến; Android chỉ xin quyền khi bạn dùng đúng công cụ.', compare: 'So sánh Android và PWA', language: 'Ngôn ngữ', languageHint: 'Có tiếng Anh, Việt, Trung và Tây Ban Nha.', tester: 'Tham gia tester Google Play', testerHint: 'Mở nhóm tester trong trình duyệt để nhận liên kết đăng ký closed test.', counters: 'Bộ đếm sử dụng ẩn danh', countersHint: 'Chia sẻ tổng số lần mở công cụ, bấm hữu ích và chia sẻ. PureHub không gửi ID người dùng, ID thiết bị, nội dung hoặc IP lưu trữ.', dnt: 'Đã tắt vì trình duyệt đang bật Không theo dõi.', privacyPromise: 'Cam kết quyền riêng tư', privacyPromiseHint: 'PureHub không có quảng cáo và xử lý dữ liệu trên thiết bị khi có thể. Quyền camera, micro và cảm biến chỉ được yêu cầu khi công cụ thực sự cần.' },
    community: { eyebrow: 'Được xây cùng cộng đồng', title: 'PureHub thuộc về mọi người', intro: 'Không mã Pro, không tường phí và không quảng cáo. Telegram giữ mọi người kết nối, còn GitHub giúp sản phẩm minh bạch và mở.', telegram: 'Cộng đồng Telegram', telegramHint: 'Trao đổi ý tưởng, nhận cập nhật và nhận hỗ trợ từ cộng đồng PureHub.', openTelegram: 'Mở Telegram', discussions: 'Thảo luận GitHub', discussionsHint: 'Đặt câu hỏi, gửi góp ý, theo dõi thông báo và cùng định hình lộ trình.', joinDiscussions: 'Vào thảo luận', bug: 'Báo lỗi', bugHint: 'Gửi thiết bị, công cụ và các bước để cộng đồng có thể tái hiện lỗi.', createIssue: 'Tạo báo lỗi', suggest: 'Đề xuất mini-app', suggestHint: 'Đề xuất một công cụ nhỏ, hữu ích, ưu tiên cục bộ để luôn miễn phí và không quảng cáo.', shareIdea: 'Gửi ý tưởng', earlyEyebrow: 'Tester sớm', earlyTitle: 'Cùng hoàn thiện các công cụ chủ lực', earlyHint: 'Thử trên điện thoại thật và báo một điều hoạt động tốt, gây khó hiểu hoặc bị lỗi. Mục tiêu đầu tiên là 20 báo cáo thiết bị hữu ích.', goal: 'Mục tiêu 20 báo cáo', toolTested: 'Công cụ đã thử', deviceReport: 'Báo cáo thiết bị', devicePlaceholder: 'Android 14 / Samsung A54 — thao tác rõ ràng nhưng khó tìm nút âm thanh.', send: 'Gửi báo cáo', sending: 'Đang gửi...', sent: 'Cảm ơn. Báo cáo ẩn danh của bạn đã vào hộp hỗ trợ cộng đồng.', sentHint: 'Cảm ơn', sendError: 'Không gửi được báo cáo. Hãy thử lại hoặc dùng GitHub Discussions.', privacyNote: 'Không cần tài khoản. Không nhập tên, email, số điện thoại hoặc thông tin cá nhân khác.', roadmap: 'Bình chọn lộ trình cộng đồng', roadmapHint: 'Chọn mini-app cần nhận đợt nâng cấp sâu tiếp theo.', votes: 'phiếu', yourVote: 'Phiếu của bạn', loading: 'Đang tải lộ trình…', unavailable: 'Lộ trình tạm thời chưa khả dụng.', voteNote: 'Một phiếu chỉ được lưu trong trình duyệt này. Không thu thập tài khoản hay định danh cá nhân.', getAndroid: 'Tải PureHub cho Android', releaseHint: 'APK đã ký, mã kiểm tra và nhật ký phát hành', contribute: 'Cách đóng góp', testFlows: 'Thử luồng ứng dụng và cộng đồng', improveTranslations: 'Cải thiện bản dịch', share: 'Chia sẻ PureHub cho người cần dùng' },
  },
  zh: {
    shell: { skip: '跳至内容', theme: '切换主题', communityUtilities: '社区工具', freeForever: '永久免费', freePromise: '无广告，无强制账户，与社区一起开源。', android: 'Android', privacy: '隐私', terms: '条款', openSource: '开源' },
    settings: { eyebrow: 'PureHub 偏好设置', title: '设置', appearance: '外观', appearanceHint: '选择最适合您的主题。', system: '跟随系统', light: '浅色', dark: '深色', privacyCenter: '打开隐私与信任中心', privacyCenterHint: '权限、加密套件备份和本地数据控制', platform: '平台可用性', platformHint: 'PureHub 在 Android 和此 PWA 上各有 26 个工具。浏览器无法静默清理文件、更改壁纸或访问全部设备传感器；Android 仅会在您使用相应工具时请求权限。', compare: '比较 Android 和 PWA', language: '语言', languageHint: '提供英语、越南语、中文和西班牙语。', tester: '加入 Google Play 测试者', testerHint: '在浏览器中打开测试者群组，以获取封闭测试加入链接。', counters: '匿名使用计数', countersHint: '分享工具打开、有用点击和分享的汇总数。PureHub 不会发送用户 ID、设备 ID、内容或保存的 IP。', dnt: '由于浏览器启用了“禁止跟踪”，此功能已关闭。', privacyPromise: '隐私承诺', privacyPromiseHint: 'PureHub 没有广告，并尽可能在设备上处理数据。只有工具确实需要时，才会请求相机、麦克风和传感器权限。' },
    community: { eyebrow: '社区共建', title: 'PureHub 属于每个人', intro: '没有 Pro 代码、没有付费墙、没有广告。Telegram 让大家保持联系，GitHub 让产品保持透明和开放。', telegram: 'Telegram 社区', telegramHint: '讨论想法、接收更新，并获得 PureHub 社区帮助。', openTelegram: '打开 Telegram', discussions: 'GitHub 讨论区', discussionsHint: '提问、分享反馈、关注公告，并一起塑造路线图。', joinDiscussions: '加入讨论', bug: '报告问题', bugHint: '提供设备、工具和复现步骤，方便社区重现问题。', createIssue: '创建问题', suggest: '建议 mini-app', suggestHint: '建议一个小巧实用、本地优先、始终免费无广告的工具。', shareIdea: '分享想法', earlyEyebrow: '早期测试者', earlyTitle: '帮助打磨旗舰工具', earlyHint: '请在真实手机上测试，并报告一件好用、令人困惑或失败的事情。首个目标是 20 份有用的设备报告。', goal: '目标 20 份报告', toolTested: '已测试工具', deviceReport: '设备报告', devicePlaceholder: 'Android 14 / Samsung A54 — 控件清晰，但声音按钮不容易找到。', send: '发送报告', sending: '正在发送...', sent: '感谢。您的匿名报告已进入社区支持收件箱。', sentHint: '感谢', sendError: '报告无法发送。请重试或使用 GitHub Discussions。', privacyNote: '无需账户。请勿填写姓名、邮箱、电话号码或其他个人信息。', roadmap: '社区路线图投票', roadmapHint: '选择下一个应获得深度升级的 mini-app。', votes: '票', yourVote: '您的投票', loading: '正在加载路线图…', unavailable: '路线图暂时不可用。', voteNote: '每个浏览器仅保存一票。不会收集账户或个人标识。', getAndroid: '获取 Android 版 PureHub', releaseHint: '已签名 APK、校验和与更新日志', contribute: '参与方式', testFlows: '测试应用和社区流程', improveTranslations: '改进翻译', share: '将 PureHub 分享给需要的人' },
  },
  es: {
    shell: { skip: 'Saltar al contenido', theme: 'Cambiar tema', communityUtilities: 'Utilidades comunitarias', freeForever: 'Gratis para siempre', freePromise: 'Sin anuncios. Sin cuenta obligatoria. Código abierto con la comunidad.', android: 'Android', privacy: 'Privacidad', terms: 'Términos', openSource: 'Código abierto' },
    settings: { eyebrow: 'Preferencias de PureHub', title: 'Ajustes', appearance: 'Apariencia', appearanceHint: 'Elige el tema que mejor funcione para ti.', system: 'Sistema', light: 'Claro', dark: 'Oscuro', privacyCenter: 'Abrir Centro de privacidad y confianza', privacyCenterHint: 'Permisos, copia cifrada del conjunto y controles de datos locales', platform: 'Disponibilidad por plataforma', platformHint: 'PureHub tiene 26 herramientas en Android y 26 en esta PWA. El navegador no puede limpiar archivos, cambiar el fondo ni acceder a todos los sensores en silencio; Android solicita esos permisos solo al usar la herramienta correspondiente.', compare: 'Comparar Android y PWA', language: 'Idioma', languageHint: 'Disponibles inglés, vietnamita, chino y español.', tester: 'Unirse a testers de Google Play', testerHint: 'Abre el grupo de testers en tu navegador para recibir el enlace de acceso a la prueba cerrada.', counters: 'Contadores de uso anónimos', countersHint: 'Comparte totales de aperturas, toques útiles y compartidos. PureHub no envía un ID de usuario, ID de dispositivo, contenido ni IP almacenada.', dnt: 'Desactivado porque No rastrear está activado en tu navegador.', privacyPromise: 'Compromiso de privacidad', privacyPromiseHint: 'PureHub no tiene anuncios y procesa datos en el dispositivo siempre que es posible. Los permisos de cámara, micrófono y sensores solo se solicitan cuando una herramienta realmente los necesita.' },
    community: { eyebrow: 'Creado con la comunidad', title: 'PureHub pertenece a todos', intro: 'Sin códigos Pro, sin muros de pago y sin anuncios. Telegram mantiene conectadas a las personas y GitHub mantiene el producto transparente y abierto.', telegram: 'Comunidad de Telegram', telegramHint: 'Habla de ideas, recibe novedades y obtén ayuda de la comunidad PureHub.', openTelegram: 'Abrir Telegram', discussions: 'Debates de GitHub', discussionsHint: 'Haz preguntas, comparte comentarios, sigue anuncios y ayuda a definir la hoja de ruta.', joinDiscussions: 'Unirse a debates', bug: 'Informar un error', bugHint: 'Comparte el dispositivo, la herramienta y los pasos para que la comunidad pueda reproducir el problema.', createIssue: 'Crear incidencia', suggest: 'Sugerir una mini-app', suggestHint: 'Sugiere una herramienta pequeña, útil y local que pueda seguir siendo gratis y sin anuncios.', shareIdea: 'Compartir idea', earlyEyebrow: 'Testers iniciales', earlyTitle: 'Ayuda a pulir nuestras herramientas principales', earlyHint: 'Prueba en tu teléfono real e informa algo que funcionó, fue confuso o falló. El primer objetivo son 20 informes útiles de dispositivos.', goal: 'Meta: 20 informes', toolTested: 'Herramienta probada', deviceReport: 'Informe del dispositivo', devicePlaceholder: 'Android 14 / Samsung A54 — los controles eran claros, pero costaba encontrar el botón de sonido.', send: 'Enviar informe', sending: 'Enviando...', sent: 'Gracias. Tu informe anónimo está ahora en la bandeja de soporte de la comunidad.', sentHint: 'Gracias', sendError: 'No se pudo enviar el informe. Inténtalo de nuevo o usa los debates de GitHub.', privacyNote: 'No se necesita cuenta. No incluyas tu nombre, correo, teléfono ni otra información personal.', roadmap: 'Votación de hoja de ruta', roadmapHint: 'Elige la mini-app que debe recibir la próxima mejora profunda.', votes: 'votos', yourVote: 'Tu voto', loading: 'Cargando hoja de ruta…', unavailable: 'La hoja de ruta no está disponible temporalmente.', voteNote: 'Solo se guarda un voto en este navegador. No se recopilan cuentas ni identificadores personales.', getAndroid: 'Obtener PureHub para Android', releaseHint: 'APK firmados, sumas de verificación y registro de cambios', contribute: 'Formas de contribuir', testFlows: 'Probar la app y los flujos de comunidad', improveTranslations: 'Mejorar traducciones', share: 'Compartir PureHub con quien lo necesite' },
  },
}

export function getUiCopy(locale: LocaleCode) {
  return uiCopy[locale]
}
