import { useEffect, useMemo, useState } from 'react'
import { Download, PieChart, Plus, ReceiptText, Share2, ShieldCheck, Trash2, Users, Wallet } from 'lucide-react'
import { expenseRepository, type ExpenseRecord } from '../../../lib/db/purehub-db'
import { ActionButton, FormInput, FormTextArea } from '../MiniAppPrimitives'

type Mode = 'expenses' | 'split'
const CATEGORIES = ['Food', 'Transport', 'Home', 'Health', 'Fun', 'General']
type CurrencyCode = 'USD' | 'EUR' | 'GBP' | 'VND' | 'JPY'
const CURRENCIES: CurrencyCode[] = ['USD', 'EUR', 'GBP', 'VND', 'JPY']
const currency = { format: (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: (typeof window === 'undefined' ? 'USD' : localStorage.getItem('purehub.finance.currency') || 'USD') }).format(value) }

export default function FinanceSuiteSurface({ mode }: { mode: Mode }) {
  return <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
    <header className="bg-gradient-to-br from-amber-50 via-white to-emerald-50 p-5 dark:from-amber-950/35 dark:via-slate-900 dark:to-emerald-950/30">
      <div className="flex items-start gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950">{mode === 'expenses' ? <Wallet className="size-6" /> : <Users className="size-6" />}</span><div className="min-w-0 flex-1"><p className="text-[11px] font-black tracking-[.2em] text-amber-700 dark:text-amber-300">PRIVATE MONEY TOOLS</p><h2 className="text-2xl font-black text-slate-950 dark:text-white">{mode === 'expenses' ? 'Expense Tracker' : 'Bill Splitter'}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{mode === 'expenses' ? 'A calm local ledger with useful trends and export.' : 'Settle a shared bill clearly without sign-up or ads.'}</p></div><ShieldCheck className="hidden size-5 text-emerald-600 sm:block" /></div>
      <nav className="mt-4 grid grid-cols-2 gap-2"><a href="/en/expense-tracker" className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border text-sm font-black ${mode === 'expenses' ? 'border-amber-400 bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950' : 'border-slate-200 bg-white/70 dark:border-slate-700 dark:bg-slate-800'}`}><PieChart className="size-4" />Expenses</a><a href="/en/bill-splitter" className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border text-sm font-black ${mode === 'split' ? 'border-amber-400 bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950' : 'border-slate-200 bg-white/70 dark:border-slate-700 dark:bg-slate-800'}`}><ReceiptText className="size-4" />Split bill</a></nav>
    </header>
    <div className="p-4 sm:p-5">{mode === 'expenses' ? <ExpenseLedger /> : <BillSplit />}</div>
  </section>
}

function ExpenseLedger() {
  const [records, setRecords] = useState<ExpenseRecord[]>([])
  const [title, setTitle] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('Food'); const [note, setNote] = useState('')
  const [currencyCode, setCurrencyCode] = useState<CurrencyCode>(() => (localStorage.getItem('purehub.finance.currency') as CurrencyCode) || 'USD')
  const [budget, setBudget] = useState(() => Number(localStorage.getItem('purehub.finance.monthly-budget') ?? 0))
  const money = useMemo(() => new Intl.NumberFormat(undefined, { style: 'currency', currency: currencyCode }), [currencyCode])
  useEffect(() => { void expenseRepository.list().then((rows) => setRecords(rows.reverse())) }, [])
  const total = useMemo(() => records.reduce((sum, item) => sum + item.amount, 0), [records])
  const monthTotal = useMemo(() => { const now = new Date(); return records.filter((item) => { const date = new Date(item.createdAt); return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear() }).reduce((sum, item) => sum + item.amount, 0) }, [records])
  const categoryTotals = useMemo(() => Object.entries(records.reduce<Record<string, number>>((result, item) => ({ ...result, [item.category]: (result[item.category] ?? 0) + item.amount }), {})).sort((a, b) => b[1] - a[1]), [records])
  const budgetProgress = budget > 0 ? Math.min(1, monthTotal / budget) : 0
  const add = async () => { const value = Number(amount); if (!title.trim() || !Number.isFinite(value) || value <= 0) return; const row = { id: crypto.randomUUID(), title: title.trim(), amount: value, category, note: note.trim(), createdAt: new Date().toISOString() }; await expenseRepository.put(row); setRecords((current) => [row, ...current]); setTitle(''); setAmount(''); setNote('') }
  const exportCsv = () => { const data = ['Date,Title,Category,Amount,Note', ...records.map((item) => [item.createdAt, item.title, item.category, item.amount, item.note ?? ''].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([data], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'purehub-expenses.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500) }
  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><strong className="block text-sm">Money dashboard</strong><span className="text-xs text-slate-500">Stored only on this device</span></div><select aria-label="Currency" value={currencyCode} onChange={(event) => { const value = event.target.value as CurrencyCode; setCurrencyCode(value); localStorage.setItem('purehub.finance.currency', value) }} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-black dark:border-slate-600 dark:bg-slate-900">{CURRENCIES.map((item) => <option key={item}>{item}</option>)}</select></div>
    <div className="grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-950 p-4 text-white"><span className="text-xs text-slate-400">This month</span><strong className="mt-1 block text-2xl">{money.format(monthTotal)}</strong></div><div className="rounded-2xl bg-amber-50 p-4 text-amber-950 dark:bg-amber-950/35 dark:text-amber-100"><span className="text-xs opacity-70">All time</span><strong className="mt-1 block text-2xl">{money.format(total)}</strong></div></div>
    <details className="rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><summary className="min-h-11 cursor-pointer list-none py-3 text-sm font-black">Monthly budget {budget > 0 ? `• ${Math.round(budgetProgress * 100)}% used` : '• not set'}</summary><div className="mt-2"><FormInput aria-label="Monthly budget" inputMode="decimal" value={budget || ''} onChange={(event) => { const value = Math.max(0, Number(event.target.value) || 0); setBudget(value); localStorage.setItem('purehub.finance.monthly-budget', String(value)) }} placeholder="Set a monthly budget" />{budget > 0 ? <><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${budgetProgress >= 1 ? 'bg-rose-500' : 'bg-amber-500'}`} style={{ width: `${budgetProgress * 100}%` }} /></div><p className="mt-2 text-xs text-slate-500">{money.format(Math.max(0, budget - monthTotal))} remaining this month</p></> : null}</div></details>
    <details className="rounded-2xl border border-slate-200 p-4 open:bg-slate-50 dark:border-slate-700 dark:open:bg-slate-950" open={!records.length}><summary className="cursor-pointer font-black">Add expense</summary><div className="mt-4 space-y-3"><FormInput value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What did you buy?" /><div className="grid grid-cols-2 gap-2"><FormInput inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Amount" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold dark:border-slate-600 dark:bg-slate-900">{CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></div><FormTextArea rows={2} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note" /><ActionButton className="w-full" onClick={() => void add()} disabled={!title.trim() || !(Number(amount) > 0)}><Plus className="mr-2 inline size-4" />Save locally</ActionButton></div></details>
    {categoryTotals.length ? <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center justify-between"><strong>Spending mix</strong><button title="Export CSV" onClick={exportCsv} className="grid size-9 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><Download className="size-4" /></button></div><div className="mt-3 space-y-2">{categoryTotals.slice(0, 5).map(([name, value]) => <div key={name}><div className="flex justify-between text-xs font-bold"><span>{name}</span><span>{currency.format(value)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-amber-500" style={{ width: `${Math.max(5, value / total * 100)}%` }} /></div></div>)}</div></div> : null}
    <div className="space-y-2">{records.length ? records.map((item) => <article key={item.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><span className="grid size-10 place-items-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-200"><ReceiptText className="size-5" /></span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.title}</strong><span className="text-xs text-slate-500">{item.category} · {new Date(item.createdAt).toLocaleDateString()}</span></div><strong>{currency.format(item.amount)}</strong><button title="Delete" onClick={() => void expenseRepository.remove(item.id).then(() => setRecords((current) => current.filter((row) => row.id !== item.id)))} className="grid size-9 place-items-center rounded-xl text-rose-600"><Trash2 className="size-4" /></button></article>) : <p className="rounded-2xl border border-dashed border-slate-300 py-10 text-center text-sm text-slate-500 dark:border-slate-700">Your private ledger is empty.</p>}</div>
  </div>
}

function BillSplit() {
  const [bill, setBill] = useState('60'); const [tax, setTax] = useState('5'); const [tip, setTip] = useState('10'); const [names, setNames] = useState(['Alex', 'Sam', 'Taylor'])
  const [currencyCode, setCurrencyCode] = useState<CurrencyCode>(() => (localStorage.getItem('purehub.finance.currency') as CurrencyCode) || 'USD')
  const subtotal = Math.max(0, Number(bill) || 0); const taxValue = Math.max(0, Number(tax) || 0); const tipValue = subtotal * Math.max(0, Number(tip) || 0) / 100; const total = subtotal + taxValue + tipValue; const each = total / Math.max(1, names.length)
  const summary = `PureHub Bill Splitter\nTotal: ${currency.format(total)}\n${names.map((name) => `${name || 'Guest'}: ${currency.format(each)}`).join('\n')}`
  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><strong className="block text-sm">Settlement currency</strong><span className="text-xs text-slate-500">No conversion or account required</span></div><select aria-label="Currency" value={currencyCode} onChange={(event) => { const value = event.target.value as CurrencyCode; setCurrencyCode(value); localStorage.setItem('purehub.finance.currency', value) }} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-black dark:border-slate-600 dark:bg-slate-900">{CURRENCIES.map((item) => <option key={item}>{item}</option>)}</select></div>
    <div className="rounded-[22px] bg-slate-950 p-5 text-white"><div className="flex justify-between"><span className="text-sm text-slate-400">Group total</span><Users className="size-5 text-amber-300" /></div><strong className="mt-2 block text-4xl">{currency.format(total)}</strong><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><span className="text-xs text-slate-400">Each person</span><strong className="mt-1 block text-xl text-amber-300">{currency.format(each)}</strong></div><div className="rounded-xl bg-white/10 p-3"><span className="text-xs text-slate-400">People</span><strong className="mt-1 block text-xl">{names.length}</strong></div></div></div>
    <div className="grid grid-cols-3 gap-2"><label className="text-xs font-bold">Bill<FormInput inputMode="decimal" value={bill} onChange={(event) => setBill(event.target.value)} className="mt-1" /></label><label className="text-xs font-bold">Tax<FormInput inputMode="decimal" value={tax} onChange={(event) => setTax(event.target.value)} className="mt-1" /></label><label className="text-xs font-bold">Tip %<FormInput inputMode="decimal" value={tip} onChange={(event) => setTip(event.target.value)} className="mt-1" /></label></div>
    <div><div className="flex items-center justify-between"><strong>People</strong><button onClick={() => names.length < 12 && setNames((current) => [...current, `Guest ${current.length + 1}`])} className="flex min-h-10 items-center gap-1 rounded-xl bg-amber-50 px-3 text-xs font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200"><Plus className="size-4" />Add</button></div><div className="mt-3 space-y-2">{names.map((name, index) => <div key={index} className="flex items-center gap-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-amber-100 text-xs font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200">{index + 1}</span><FormInput value={name} onChange={(event) => setNames((current) => current.map((item, position) => position === index ? event.target.value : item))} /><strong className="min-w-20 text-right text-sm">{currency.format(each)}</strong>{names.length > 1 ? <button title="Remove" onClick={() => setNames((current) => current.filter((_, position) => position !== index))} className="grid size-9 shrink-0 place-items-center text-rose-600"><Trash2 className="size-4" /></button> : null}</div>)}</div></div>
    <ActionButton className="flex w-full items-center justify-center" onClick={() => navigator.share ? void navigator.share({ title: 'Bill split', text: summary }) : void navigator.clipboard.writeText(summary)}><Share2 className="mr-2 inline size-4" />Share settlement</ActionButton>
    <p className="rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">Equal split mode keeps the result fast and transparent. Advanced item assignments and reusable presets are available in the Android app.</p>
  </div>
}
