import { useEffect, useMemo, useState } from 'react'
import type { ChangeEvent } from 'react'
import { Download, LockKeyhole, PieChart, Plus, ReceiptText, ScanLine, Share2, ShieldCheck, Trash2, Upload, Users, Wallet } from 'lucide-react'
import { expenseRepository, type ExpenseRecord } from '../../../lib/db/purehub-db'
import { decryptBackup, downloadBackup, encryptBackup } from '../../../lib/encrypted-backup'
import { recognizeReceipt } from '../../../lib/receipt-ocr'
import { markToolSuccess } from '../../../lib/tool-success'
import { trackProductEvent } from '../../../lib/community-api'
import { ActionButton, FormInput, FormTextArea } from '../MiniAppPrimitives'
import { buildMiniAppPath } from '../../../i18n/routing'
import { normalizeLocale } from '../../../i18n/locales'

type Mode = 'expenses' | 'split'
const CATEGORIES = ['Food', 'Transport', 'Home', 'Health', 'Fun', 'General']
type CurrencyCode = 'USD' | 'EUR' | 'GBP' | 'VND' | 'JPY'
const CURRENCIES: CurrencyCode[] = ['USD', 'EUR', 'GBP', 'VND', 'JPY']
const currency = { format: (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: (typeof window === 'undefined' ? 'USD' : localStorage.getItem('purehub.finance.currency') || 'USD') }).format(value) }

export default function FinanceSuiteSurface({ mode }: { mode: Mode }) {
  const locale = normalizeLocale(window.location.pathname.split('/')[1])
  return <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
    <header className="bg-gradient-to-br from-amber-50 via-white to-emerald-50 p-5 dark:from-amber-950/35 dark:via-slate-900 dark:to-emerald-950/30">
      <div className="flex items-start gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950">{mode === 'expenses' ? <Wallet className="size-6" /> : <Users className="size-6" />}</span><div className="min-w-0 flex-1"><p className="text-[11px] font-black tracking-[.2em] text-amber-700 dark:text-amber-300">PRIVATE MONEY TOOLS</p><h2 className="text-2xl font-black text-slate-950 dark:text-white">{mode === 'expenses' ? 'Expense Tracker' : 'Bill Splitter'}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{mode === 'expenses' ? 'A calm local ledger with useful trends and export.' : 'Settle a shared bill clearly without sign-up or ads.'}</p></div><ShieldCheck className="hidden size-5 text-emerald-600 sm:block" /></div>
      <nav className="mt-4 grid grid-cols-2 gap-2"><a href={buildMiniAppPath(locale, 'expense-tracker')} className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border text-sm font-black ${mode === 'expenses' ? 'border-amber-400 bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950' : 'border-slate-200 bg-white/70 dark:border-slate-700 dark:bg-slate-800'}`}><PieChart className="size-4" />Expenses</a><a href={buildMiniAppPath(locale, 'bill-splitter')} className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border text-sm font-black ${mode === 'split' ? 'border-amber-400 bg-amber-600 text-white dark:bg-amber-300 dark:text-slate-950' : 'border-slate-200 bg-white/70 dark:border-slate-700 dark:bg-slate-800'}`}><ReceiptText className="size-4" />Split bill</a></nav>
    </header>
    <div className="p-4 sm:p-5">{mode === 'expenses' ? <ExpenseLedger /> : <BillSplit />}</div>
  </section>
}

function ExpenseLedger() {
  const [records, setRecords] = useState<ExpenseRecord[]>([])
  const [title, setTitle] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('Food'); const [note, setNote] = useState('')
  const [transactionType, setTransactionType] = useState<'expense' | 'income'>('expense'); const [wallet, setWallet] = useState('Cash')
  const [currencyCode, setCurrencyCode] = useState<CurrencyCode>(() => (localStorage.getItem('purehub.finance.currency') as CurrencyCode) || 'USD')
  const [budget, setBudget] = useState(() => Number(localStorage.getItem('purehub.finance.monthly-budget') ?? 0))
  const [backupPassphrase, setBackupPassphrase] = useState('')
  const [dataNotice, setDataNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const [receiptStatus, setReceiptStatus] = useState('')
  const [recordQuery, setRecordQuery] = useState('')
  const [recordCategory, setRecordCategory] = useState('All')
  const money = useMemo(() => new Intl.NumberFormat(undefined, { style: 'currency', currency: currencyCode }), [currencyCode])
  const load = async () => setRecords((await expenseRepository.list()).reverse())
  useEffect(() => { void load() }, [])
  const monthRows = useMemo(() => { const now = new Date(); return records.filter((item) => { const date = new Date(item.createdAt); return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear() }) }, [records])
  const monthExpenses = useMemo(() => monthRows.filter((item) => item.transactionType !== 'income').reduce((sum, item) => sum + item.amount, 0), [monthRows])
  const monthIncome = useMemo(() => monthRows.filter((item) => item.transactionType === 'income').reduce((sum, item) => sum + item.amount, 0), [monthRows])
  const totalExpenses = useMemo(() => records.filter((item) => item.transactionType !== 'income').reduce((sum, item) => sum + item.amount, 0), [records])
  const categoryTotals = useMemo(() => Object.entries(monthRows.filter((item) => item.transactionType !== 'income').reduce<Record<string, number>>((result, item) => ({ ...result, [item.category]: (result[item.category] ?? 0) + item.amount }), {})).sort((a, b) => b[1] - a[1]), [monthRows])
  const budgetProgress = budget > 0 ? Math.min(1, monthExpenses / budget) : 0
  const visibleRecords = useMemo(() => records.filter((item) => {
    const categoryMatches = recordCategory === 'All' || item.category === recordCategory
    const text = `${item.title} ${item.note ?? ''} ${item.wallet ?? 'Cash'}`.toLocaleLowerCase()
    return categoryMatches && text.includes(recordQuery.trim().toLocaleLowerCase())
  }), [recordCategory, recordQuery, records])
  const add = async () => { const value = Number(amount); if (!title.trim() || !Number.isFinite(value) || value <= 0) return; const row: ExpenseRecord = { id: crypto.randomUUID(), title: title.trim(), amount: value, category, transactionType, wallet: wallet.trim() || 'Cash', note: note.trim(), createdAt: new Date().toISOString() }; await expenseRepository.put(row); setRecords((current) => [row, ...current]); setTitle(''); setAmount(''); setNote(''); markToolSuccess('expense-tracker', { headline: 'Transaction saved locally', detail: `${row.title} was added to this device-only ledger.`, shareText: 'I saved a private money record locally with no account or financial-data upload.' }) }
  const exportCsv = () => { const data = ['Date,Title,Type,Category,Wallet,Amount,Note', ...records.map((item) => [item.createdAt, item.title, item.transactionType ?? 'expense', item.category, item.wallet ?? 'Cash', item.amount, item.note ?? ''].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([data], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'purehub-money-ledger.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500); markToolSuccess('expense-tracker', { headline: 'Money CSV exported', detail: `${records.length} local transaction${records.length === 1 ? '' : 's'} were exported to a spreadsheet-friendly file.`, shareText: 'I exported my money ledger locally with PureHub.' }) }
  const scanReceipt = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file) return
    setBusy(true); setReceiptStatus('Reading receipt locally...')
    try {
      const receipt = await recognizeReceipt(file, (progress) => setReceiptStatus(`Reading receipt locally... ${Math.round(progress * 100)}%`))
      setTitle(receipt.merchant); if (receipt.total != null) setAmount(String(receipt.total))
      setNote([receipt.tax != null ? `Tax: ${receipt.tax}` : '', receipt.lines.length ? `${receipt.lines.length} item lines detected` : ''].filter(Boolean).join(' - '))
      setReceiptStatus(receipt.total == null ? 'Text detected, but the total needs review.' : 'Receipt fields filled. Review before saving.')
    } catch { setReceiptStatus('Could not read this receipt. Try a sharper, well-lit image.') } finally { setBusy(false) }
  }
  const exportEncrypted = async () => {
    setBusy(true)
    try { downloadBackup(await encryptBackup('expense-tracker', { records, currencyCode, budget }, backupPassphrase), `purehub-expenses-${new Date().toISOString().slice(0, 10)}.purehub`); setDataNotice('Encrypted expense backup saved.'); markToolSuccess('expense-tracker', { headline: 'Encrypted expense backup saved', detail: 'Your ledger backup was encrypted locally before download.', shareText: 'I backed up my private expense data with PureHub.' }) }
    catch (error) { setDataNotice(error instanceof Error ? error.message : 'Could not create the backup.') }
    finally { setBusy(false) }
  }
  const importEncrypted = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file) return
    setBusy(true)
    try {
      const payload = await decryptBackup<{ records: ExpenseRecord[]; currencyCode?: CurrencyCode; budget?: number }>(await file.text(), 'expense-tracker', backupPassphrase)
      if (!Array.isArray(payload.records) || payload.records.some((item) => !item.id || !item.title || !Number.isFinite(item.amount) || !item.createdAt)) throw new Error('The expense backup is malformed.')
      await expenseRepository.importBackup(payload.records)
      if (payload.currencyCode && CURRENCIES.includes(payload.currencyCode)) { setCurrencyCode(payload.currencyCode); localStorage.setItem('purehub.finance.currency', payload.currencyCode) }
      if (Number.isFinite(payload.budget)) { const nextBudget = Math.max(0, Number(payload.budget)); setBudget(nextBudget); localStorage.setItem('purehub.finance.monthly-budget', String(nextBudget)) }
      await load(); setDataNotice(`Imported ${payload.records.length} encrypted expense records.`)
    } catch (error) { setDataNotice(error instanceof Error ? error.message : 'Could not decrypt this backup.') }
    finally { setBusy(false) }
  }
  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><strong className="block text-sm">Money dashboard</strong><span className="text-xs text-slate-500">Stored only on this device</span></div><select aria-label="Currency" value={currencyCode} onChange={(event) => { const value = event.target.value as CurrencyCode; setCurrencyCode(value); localStorage.setItem('purehub.finance.currency', value) }} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-black dark:border-slate-600 dark:bg-slate-900">{CURRENCIES.map((item) => <option key={item}>{item}</option>)}</select></div>
    <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-emerald-50 p-3 text-emerald-950 dark:bg-emerald-950/35 dark:text-emerald-100"><span className="text-xs opacity-70">Income</span><strong className="mt-1 block truncate text-lg">{money.format(monthIncome)}</strong></div><div className="rounded-2xl bg-rose-50 p-3 text-rose-950 dark:bg-rose-950/35 dark:text-rose-100"><span className="text-xs opacity-70">Expenses</span><strong className="mt-1 block truncate text-lg">{money.format(monthExpenses)}</strong></div><div className="rounded-2xl bg-slate-950 p-3 text-white"><span className="text-xs text-slate-400">Balance</span><strong className="mt-1 block truncate text-lg">{money.format(monthIncome - monthExpenses)}</strong></div></div>
    <details className="rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><summary className="min-h-11 cursor-pointer list-none py-3 text-sm font-black">Monthly expense budget {budget > 0 ? `• ${Math.round(budgetProgress * 100)}% used` : '• not set'}</summary><div className="mt-2"><FormInput aria-label="Monthly budget" inputMode="decimal" value={budget || ''} onChange={(event) => { const value = Math.max(0, Number(event.target.value) || 0); setBudget(value); localStorage.setItem('purehub.finance.monthly-budget', String(value)) }} placeholder="Set a monthly expense budget" />{budget > 0 ? <><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${budgetProgress >= 1 ? 'bg-rose-500' : 'bg-amber-500'}`} style={{ width: `${budgetProgress * 100}%` }} /></div><p className="mt-2 text-xs text-slate-500">{money.format(Math.max(0, budget - monthExpenses))} remaining this month</p></> : null}</div></details>
    <details className="rounded-2xl border border-slate-200 p-4 open:bg-slate-50 dark:border-slate-700 dark:open:bg-slate-950" open={!records.length}><summary className="cursor-pointer font-black">Add transaction</summary><div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-2"><button onClick={() => setTransactionType('expense')} className={`min-h-11 rounded-xl text-sm font-black ${transactionType === 'expense' ? 'bg-rose-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>Expense</button><button onClick={() => setTransactionType('income')} className={`min-h-11 rounded-xl text-sm font-black ${transactionType === 'income' ? 'bg-emerald-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>Income</button></div>{transactionType === 'expense' ? <label className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border border-amber-300 bg-amber-50 px-3 text-sm font-black text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100 ${busy ? 'pointer-events-none opacity-50' : 'cursor-pointer'}`}><ScanLine className="size-4" />Scan receipt locally<input type="file" accept="image/*" capture="environment" className="sr-only" onChange={(event) => void scanReceipt(event)} /></label> : null}{receiptStatus ? <p className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{receiptStatus}</p> : null}<FormInput value={title} onChange={(event) => setTitle(event.target.value)} placeholder={transactionType === 'income' ? 'Salary, refund, freelance...' : 'What did you buy?'} /><div className="grid grid-cols-2 gap-2"><FormInput inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Amount" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold dark:border-slate-600 dark:bg-slate-900">{CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></div><FormInput value={wallet} onChange={(event) => setWallet(event.target.value)} placeholder="Wallet or account" /><FormTextArea rows={2} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional note" /><ActionButton className="w-full" onClick={() => void add()} disabled={!title.trim() || !(Number(amount) > 0)}><Plus className="mr-2 inline size-4" />Save {transactionType}</ActionButton></div></details>
    <details className="rounded-2xl border border-sky-200 bg-sky-50/50 p-3 dark:border-sky-900 dark:bg-sky-950/20"><summary className="flex min-h-10 cursor-pointer list-none items-center gap-2 text-sm font-black"><LockKeyhole className="size-4 text-sky-700" />Encrypted backup and CSV</summary><div className="mt-3 space-y-3"><FormInput type="password" autoComplete="new-password" minLength={12} maxLength={256} value={backupPassphrase} onChange={(event) => setBackupPassphrase(event.target.value)} placeholder="Backup passphrase (12+ characters)" /><div className="grid grid-cols-3 gap-2"><button type="button" disabled={busy || backupPassphrase.length < 12} onClick={() => void exportEncrypted()} className="flex min-h-11 items-center justify-center gap-1 rounded-xl bg-sky-700 px-2 text-xs font-bold text-white disabled:opacity-40"><Download className="size-4" />Backup</button><label className={`flex min-h-11 items-center justify-center gap-1 rounded-xl border border-slate-300 px-2 text-xs font-bold dark:border-slate-700 ${busy || backupPassphrase.length < 12 ? 'pointer-events-none opacity-40' : 'cursor-pointer'}`}><Upload className="size-4" />Restore<input type="file" accept=".purehub,application/json" className="sr-only" onChange={(event) => void importEncrypted(event)} /></label><button type="button" disabled={!records.length} onClick={exportCsv} className="flex min-h-11 items-center justify-center gap-1 rounded-xl border border-slate-300 px-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700"><Download className="size-4" />CSV</button></div>{dataNotice ? <p className="rounded-xl bg-white px-3 py-2 text-xs font-semibold dark:bg-slate-900">{dataNotice}</p> : null}</div></details>
    {categoryTotals.length ? <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center justify-between"><strong>Monthly spending mix</strong><button title="Export CSV" onClick={exportCsv} className="grid size-9 place-items-center rounded-xl bg-slate-100 dark:bg-slate-800"><Download className="size-4" /></button></div><div className="mt-3 space-y-2">{categoryTotals.slice(0, 5).map(([name, value]) => <div key={name}><div className="flex justify-between text-xs font-bold"><span>{name}</span><span>{currency.format(value)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-amber-500" style={{ width: `${Math.max(5, value / Math.max(1, totalExpenses) * 100)}%` }} /></div></div>)}</div></div> : null}
    {records.length ? <div className="grid grid-cols-[1fr_auto] gap-2"><FormInput aria-label="Search expenses" value={recordQuery} onChange={(event) => setRecordQuery(event.target.value)} placeholder="Search expenses" /><select aria-label="Filter expense category" value={recordCategory} onChange={(event) => setRecordCategory(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold dark:border-slate-600 dark:bg-slate-900"><option>All</option>{CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></div> : null}
    <div className="space-y-2">{visibleRecords.length ? visibleRecords.map((item) => <article key={item.id} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><span className={`grid size-10 place-items-center rounded-xl ${item.transactionType === 'income' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-200' : 'bg-rose-50 text-rose-700 dark:bg-rose-950 dark:text-rose-200'}`}><ReceiptText className="size-5" /></span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.title}</strong><span className="text-xs text-slate-500">{item.category} · {item.wallet ?? 'Cash'} · {new Date(item.createdAt).toLocaleDateString()}</span></div><strong className={item.transactionType === 'income' ? 'text-emerald-600' : 'text-rose-600'}>{item.transactionType === 'income' ? '+' : '−'}{currency.format(item.amount)}</strong><button title="Delete" onClick={() => void expenseRepository.remove(item.id).then(() => setRecords((current) => current.filter((row) => row.id !== item.id)))} className="grid size-9 place-items-center rounded-xl text-rose-600"><Trash2 className="size-4" /></button></article>) : <p className="rounded-2xl border border-dashed border-slate-300 py-10 text-center text-sm text-slate-500 dark:border-slate-700">{records.length ? 'No transaction matched the current filters.' : 'Your private ledger is empty.'}</p>}</div>
  </div>
}

function BillSplit() {
  const [bill, setBill] = useState('60'); const [tax, setTax] = useState('5'); const [tip, setTip] = useState('10'); const [names, setNames] = useState(['Alex', 'Sam', 'Taylor'])
  const [weights, setWeights] = useState([1, 1, 1]); const [splitMode, setSplitMode] = useState<'equal' | 'weighted' | 'itemized'>('equal'); const [paidBy, setPaidBy] = useState(0)
  const [items, setItems] = useState([{ id: crypto.randomUUID(), label: 'Main dish', amount: '20', person: 0 }])
  const [currencyCode, setCurrencyCode] = useState<CurrencyCode>(() => (localStorage.getItem('purehub.finance.currency') as CurrencyCode) || 'USD')
  const [receiptStatus, setReceiptStatus] = useState('')
  const [receiptBusy, setReceiptBusy] = useState(false)
  const enteredSubtotal = Math.max(0, Number(bill) || 0); const itemSubtotal = items.reduce((sum, item) => sum + Math.max(0, Number(item.amount) || 0), 0); const subtotal = splitMode === 'itemized' ? itemSubtotal : enteredSubtotal; const taxValue = Math.max(0, Number(tax) || 0); const tipValue = subtotal * Math.max(0, Number(tip) || 0) / 100; const total = subtotal + taxValue + tipValue; const each = total / Math.max(1, names.length)
  const totalWeight = weights.slice(0, names.length).reduce((sum, value) => sum + Math.max(.1, value || 1), 0)
  const itemOverhead = names.length ? (taxValue + tipValue) / names.length : 0
  const shares = names.map((_, index) => splitMode === 'equal' ? each : splitMode === 'weighted' ? total * Math.max(.1, weights[index] || 1) / totalWeight : items.filter((item) => item.person === index).reduce((sum, item) => sum + Math.max(0, Number(item.amount) || 0), 0) + itemOverhead)
  const summary = `PureHub Bill Splitter\nTotal: ${currency.format(total)}\nPaid by: ${names[paidBy] || 'Guest'}\n${names.map((name, index) => `${name || 'Guest'}: ${currency.format(shares[index])}`).join('\n')}`
  const shareSettlement = async () => {
    try {
      if (navigator.share) await navigator.share({ title: 'Bill split', text: summary })
      else await navigator.clipboard.writeText(summary)
      markToolSuccess('bill-splitter', { headline: 'Settlement shared', detail: 'A clear bill-split summary was copied or sent through your device share sheet.', shareText: 'I settled a shared bill privately with PureHub.' })
      void trackProductEvent('bill-splitter', 'share')
    } catch (error) {
      if (!(error instanceof DOMException && error.name === 'AbortError')) setReceiptStatus('Could not share this settlement. Try copying it again.')
    }
  }
  const scanReceipt = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file) return
    setReceiptBusy(true); setReceiptStatus('Reading receipt locally...')
    try {
      const receipt = await recognizeReceipt(file, (progress) => setReceiptStatus(`Reading receipt locally... ${Math.round(progress * 100)}%`))
      if (receipt.tax != null) setTax(String(receipt.tax))
      if (receipt.lines.length) {
        setItems(receipt.lines.map((line, index) => ({ id: crypto.randomUUID(), label: line.label, amount: String(line.amount), person: index % names.length })))
        setSplitMode('itemized')
      } else if (receipt.total != null) {
        setBill(String(Math.max(0, receipt.total - (receipt.tax ?? 0))))
        setSplitMode('equal')
      }
      setReceiptStatus(receipt.total == null ? 'Text detected; review the bill fields manually.' : `Detected ${receipt.lines.length} item lines. Review assignments before sharing.`)
    } catch { setReceiptStatus('Could not read this receipt. Try a sharper, well-lit image.') } finally { setReceiptBusy(false) }
  }
  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><strong className="block text-sm">Settlement currency</strong><span className="text-xs text-slate-500">No conversion or account required</span></div><select aria-label="Currency" value={currencyCode} onChange={(event) => { const value = event.target.value as CurrencyCode; setCurrencyCode(value); localStorage.setItem('purehub.finance.currency', value) }} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm font-black dark:border-slate-600 dark:bg-slate-900">{CURRENCIES.map((item) => <option key={item}>{item}</option>)}</select></div>
    <div className="rounded-[22px] bg-slate-950 p-5 text-white"><div className="flex justify-between"><span className="text-sm text-slate-400">Group total</span><Users className="size-5 text-amber-300" /></div><strong className="mt-2 block text-4xl">{currency.format(total)}</strong><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><span className="text-xs text-slate-400">Split mode</span><strong className="mt-1 block text-xl text-amber-300">{splitMode === 'equal' ? 'Equal' : splitMode === 'weighted' ? 'Weighted' : 'Itemized'}</strong></div><div className="rounded-xl bg-white/10 p-3"><span className="text-xs text-slate-400">People</span><strong className="mt-1 block text-xl">{names.length}</strong></div></div></div>
    <label className={`flex min-h-11 items-center justify-center gap-2 rounded-xl border border-amber-300 bg-amber-50 px-3 text-sm font-black text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100 ${receiptBusy ? 'pointer-events-none opacity-50' : 'cursor-pointer'}`}><ScanLine className="size-4" />Scan receipt into this split<input type="file" accept="image/*" capture="environment" className="sr-only" onChange={(event) => void scanReceipt(event)} /></label>
    {receiptStatus ? <p className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{receiptStatus}</p> : null}
    <div className="grid grid-cols-3 gap-2"><button onClick={() => setSplitMode('equal')} className={`min-h-11 rounded-xl border text-xs font-black ${splitMode === 'equal' ? 'border-amber-500 bg-amber-50 text-amber-900 dark:bg-amber-950 dark:text-amber-100' : 'border-slate-200 dark:border-slate-700'}`}>Equal</button><button onClick={() => setSplitMode('weighted')} className={`min-h-11 rounded-xl border text-xs font-black ${splitMode === 'weighted' ? 'border-amber-500 bg-amber-50 text-amber-900 dark:bg-amber-950 dark:text-amber-100' : 'border-slate-200 dark:border-slate-700'}`}>Custom</button><button onClick={() => setSplitMode('itemized')} className={`min-h-11 rounded-xl border text-xs font-black ${splitMode === 'itemized' ? 'border-amber-500 bg-amber-50 text-amber-900 dark:bg-amber-950 dark:text-amber-100' : 'border-slate-200 dark:border-slate-700'}`}>By item</button></div>
    <div className="grid grid-cols-3 gap-2"><label className="text-xs font-bold">{splitMode === 'itemized' ? 'Items total' : 'Bill'}<FormInput inputMode="decimal" value={splitMode === 'itemized' ? itemSubtotal : bill} disabled={splitMode === 'itemized'} onChange={(event) => setBill(event.target.value)} className="mt-1" /></label><label className="text-xs font-bold">Tax<FormInput inputMode="decimal" value={tax} onChange={(event) => setTax(event.target.value)} className="mt-1" /></label><label className="text-xs font-bold">Tip %<FormInput inputMode="decimal" value={tip} onChange={(event) => setTip(event.target.value)} className="mt-1" /></label></div>
    <label className="block text-xs font-bold">Who paid?<select value={paidBy} onChange={(event) => setPaidBy(Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-900">{names.map((name, index) => <option key={index} value={index}>{name || `Guest ${index + 1}`}</option>)}</select></label>
    {splitMode === 'itemized' ? <section className="rounded-2xl border border-slate-200 p-3 dark:border-slate-700"><div className="flex items-center justify-between"><div><strong className="text-sm">Item assignments</strong><p className="text-xs text-slate-500">Tax and tip are shared equally.</p></div><button onClick={() => setItems((current) => [...current, { id: crypto.randomUUID(), label: '', amount: '', person: 0 }])} className="flex min-h-10 items-center gap-1 rounded-xl bg-amber-50 px-3 text-xs font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200"><Plus className="size-4" />Item</button></div><div className="mt-3 space-y-2">{items.map((item) => <div key={item.id} className="grid grid-cols-[1fr_5rem_7rem_2.25rem] gap-2"><FormInput aria-label="Item name" value={item.label} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, label: event.target.value } : row))} placeholder="Item" /><FormInput aria-label="Item amount" inputMode="decimal" value={item.amount} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, amount: event.target.value } : row))} placeholder="0" /><select aria-label="Assign item to" value={item.person} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, person: Number(event.target.value) } : row))} className="min-h-11 rounded-xl border border-slate-300 bg-white px-2 text-xs font-bold dark:border-slate-700 dark:bg-slate-900">{names.map((name, index) => <option key={index} value={index}>{name || `Guest ${index + 1}`}</option>)}</select><button title="Remove item" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((row) => row.id !== item.id))} className="grid size-9 self-center place-items-center rounded-xl text-rose-600 disabled:opacity-30"><Trash2 className="size-4" /></button></div>)}</div></section> : null}
    <div><div className="flex items-center justify-between"><strong>People</strong><button onClick={() => { if (names.length < 12) { setNames((current) => [...current, `Guest ${current.length + 1}`]); setWeights((current) => [...current, 1]) } }} className="flex min-h-10 items-center gap-1 rounded-xl bg-amber-50 px-3 text-xs font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200"><Plus className="size-4" />Add</button></div><div className="mt-3 space-y-2">{names.map((name, index) => <div key={index} className="flex items-center gap-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-amber-100 text-xs font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200">{index + 1}</span><FormInput value={name} onChange={(event) => setNames((current) => current.map((item, position) => position === index ? event.target.value : item))} />{splitMode === 'weighted' ? <FormInput aria-label={`${name} share weight`} title="Share weight" className="max-w-16" inputMode="decimal" value={weights[index] ?? 1} onChange={(event) => setWeights((current) => current.map((item, position) => position === index ? Math.max(.1, Number(event.target.value) || 1) : item))} /> : null}<strong className="min-w-20 text-right text-sm">{currency.format(shares[index])}</strong>{names.length > 1 ? <button title="Remove" onClick={() => { setNames((current) => current.filter((_, position) => position !== index)); setWeights((current) => current.filter((_, position) => position !== index)); setPaidBy((current) => Math.min(current, names.length - 2)) }} className="grid size-9 shrink-0 place-items-center text-rose-600"><Trash2 className="size-4" /></button> : null}</div>)}</div></div>
    <ActionButton className="flex w-full items-center justify-center" onClick={() => void shareSettlement()}><Share2 className="mr-2 inline size-4" />Share settlement</ActionButton>
    <p className="rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{names[paidBy] || 'The payer'} paid the bill. Everyone else owes that person the amount shown beside their name.{splitMode === 'itemized' ? ' Item costs are assigned directly; tax and tip are shared equally.' : ''}</p>
  </div>
}
